### ISSUE TITLE
Implement a product listing page

### ISSUE THREAD

**Issue by Namsla** [Namsla/e-commerce-development-app#13]
Implement a product listing page with appropriate categorization options.
Task duration: 2hrs

**Comment by Namsla** [comment]
![Image](https://github.com/Namsla/e-commerce-development-app/assets/129420376/6fdb65c1-fc03-4cba-b016-b7c8b088f84e)



![Image](https://github.com/Namsla/e-commerce-development-app/assets/129420376/1ad96127-b780-405a-a386-f44998673796)

**Comment by Namsla** [comment]
![Image](https://github.com/Namsla/e-commerce-development-app/assets/129420376/d11de528-c6fb-417c-9d04-e9594a033d5f)

**Comment by yogeshtakeo** [comment]
Ohh ! love reading the books. Let me know if you can recommend me one. 
Also the card designs could be a little smoother.
