### ISSUE TITLE
Apply ratings on product items

### ISSUE THREAD

**Issue by Namsla** [Namsla/e-commerce-development-app#26]
Give ratings to each items out of five rating stars. Use bootstrap to achieve this goal.
Task Duration: 1hr

**Comment by Namsla** [comment]
![Image](https://github.com/Namsla/e-commerce-development-app/assets/129420376/dba70e17-212a-4cc3-a299-e644d4fc099a)

**Comment by yogeshtakeo** [comment]
Rate me better too 😊😊
