### ISSUE TITLE
create UI/UX friendly header and footer components

### ISSUE THREAD

**Issue by Namsla** [Namsla/e-commerce-development-app#7]
Create a beautiful header and footer components to be used for all the pages.  Research on e-commerce themed navbars.

Task Time: 1 day

**Comment by Namsla** [comment]
![Image](https://github.com/Namsla/e-commerce-development-app/assets/129420376/f3e9eb66-3087-4f50-a470-15871cafebfc)

**Comment by Namsla** [comment]
![Image](https://github.com/Namsla/e-commerce-development-app/assets/129420376/c84e5e76-1f48-4927-9596-f64773d8c49d)

**Comment by yogeshtakeo** [comment]
Header and Footer components looks okay.
